frontend:
  image: lyzhang1999/frontend
  tag: 4062b16
  autoscaling:
    averageUtilization: 90
backend:
  image: lyzhang1999/backend
  tag: 4062b16
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
